Inkronix_Courses_Page_Updated/blog/urls.py
from django.urls import path
from blog import views
from blog.views import BlogView, BlogAV, BlogDetailAV, WriterAV, BlogSearchView
# from django.conf.urls import url

urlpatterns = [
    path('', views.bloghome, name='blog'),
    path('blog-form', views.BlogFormView, name='blog-form'),
    path('<int:pk>', BlogView.as_view(), name='blog-page'),
    path('blog-view', BlogAV.as_view(), name='blog-view'),
    path('blog-view/<int:pk>', BlogDetailAV.as_view(), name='blog-detail'),
    path('writer', WriterAV.as_view(), name='writer'),
    path('search-view/', BlogSearchView.as_view(), name="search-view")
]

# WARNINGS:
# ?: (2_0.W001) Your URL pattern '^blog-search-result/$' [name='blog-search-result'] has a route that
# contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().

# this new admin url is awesome: http://127.0.0.1:8019/admin/blog/

Inkronix_Courses_Page_Updated/inkronix/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('courses/', include('courses.urls')),
    path('contact/', include('contact.urls')),
    path('', include('home.urls')),
    path('instructor/', include('instructor.urls')),
    path('student/', include('student.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Inkronix_Courses_Page_Updated/blog/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Writer(models.Model):

    writer_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.writer_name

class Category(models.Model):
    topic = models.CharField(max_length=100, default="python")

    def __str__(self):
        return self.topic


class Blog(models.Model):

    blog_title = models.CharField(default="Title", max_length=100)
    blog_text = models.TextField(default="My Blog", max_length=10000)
    blog_image = models.ImageField(upload_to="blog/")
    blog_date_time = models.DateTimeField(default=datetime.now)
    writer_name = models.ForeignKey(Writer, on_delete=models.CASCADE, related_name = 'writer')
    blog_category = models.ForeignKey(Category, on_delete=models.CASCADE) #default=Category.get_default_pk, related_name = "category")


    def all_blogs():
        return Blog.objects.all()

    def __str__(self):
        return self.blog_title

    def get_blogs_by_category_id(category_id):
        return Blog.objects.filter(blog_category_id=category_id)

class Comment(models.Model):

    name = models.CharField(max_length=80, default='name', blank=True)
    email = models.EmailField(default="email", blank=True)
    your_comment = models.CharField(max_length=500, default="your comment", blank=True)
    created_on = models.DateTimeField(default=datetime.now)
    active = models.BooleanField(default=False)
    blog = models.IntegerField(blank=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.your_comment, self.name)

Inkronix_Courses_Page_Updated/blog/forms.py
from django import forms
from blog.models import Comment, Blog

# Create your forms here.
class BlogForm(forms.ModelForm):

    class Meta:
        model = Blog
        # fields = '__all__'
        fields = ('blog_title', 'blog_text', 'blog_image', 'writer_name', 'blog_category')
        # exclude = ("comment",)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = ('your_comment',)
        fields = ('name', 'email', 'your_comment')
        # widgets = {'blog': forms.HiddenInput()}

# class ReactionForm(forms.ModelForm):
#     reaction = forms.ChoiceField(choices=Comment.your_reaction)

#     class Meta:
#         model = Comment
#         fields = ('reaction',)

Inkronix_Courses_Page_Updated/blog/views.py
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView

from django.http import HttpRequest, HttpResponse, request
from django.shortcuts import render, redirect
# from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.views.generic.base import View
from django.views.generic import ListView
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from blog.models import Blog, Writer, Comment, Category
from blog.serializers import BlogSerializer, WriterSerializer
from blog.forms import CommentForm, BlogForm

# blogsite homepage
def bloghome(request):

    if request.method == 'GET':
        # blogs = Blog.objects.all()
        categories = Category.objects.all()
        category_id = request.GET.get('category')
        
        if category_id:
            blogs = Blog.get_blogs_by_category_id(category_id=category_id).order_by('-blog_date_time')
        else:
            blogs = Blog.objects.all().order_by('-blog_date_time')

        paginator = Paginator(blogs, per_page=2)
        page_number = request.GET.get("page", 1)
        page_obj = paginator.get_page(page_number)
        try:
            blogs = paginator.page(page_number)
        except PageNotAnInteger:
            page_number = 1
            blogs = paginator.page(page_number)
        except EmptyPage:
            page_number = paginator.num_pages
            blogs = paginator.page(page_number)

    # return render(request, 'Blogs/blog.html', {'page_obj':page_obj, 'categories':categories})
    return render(request, 'Blogs/blog.html', {'blogs':blogs, 'page_obj':page_obj, 'categories':categories})

# add blog Blog-form-view
def BlogFormView(request):

    blog_form = BlogForm()

    if request.method == "POST":
        blog_form = BlogForm(request.POST, request.FILES)

        if blog_form.is_valid():
            blog_form.save()

            messages.success(request, ('Your blog was successfully added!'))
        else:
            messages.error(request, 'Error saving form')

        return redirect('blog')

    return render(request=request, template_name="Blogs/blog-form.html", context={'blog_form':blog_form})

# blog detail view
class BlogView(View):

    def get(self,request,pk):

        blog = Blog.objects.get(id=pk)
        comment_form = CommentForm()
        comments = Comment.objects.filter(blog = blog.id).order_by('-created_on')
        categories = Category.objects.all()
        category_id = request.GET.get('category')

        if category_id:
            blogs = Blog.get_blogs_by_category_id(category_id=category_id).order_by('-blog_date_time')
            return render(request, 'Blogs/blog.html', {'blogs':blogs, 'categories':categories})
        else:
            return render(request,'Blogs/blog-view.html', {'blog':blog, 'comment_form':comment_form, 'comments':comments, 'categories':categories})

    def post(self,request,pk):

        blog = Blog.objects.get(id=pk)
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid:
            blog_id = blog.id
            new_comment = comment_form.save(commit=False)
            new_comment.blog = blog_id
            new_comment.save()

        # messages.success(request, ('Your comment was added successfully!'))
        return redirect('blog')
        # return render(request, 'Blogs/blog-view.html', {'comment_form':comment_form})

# keyword search view
class BlogSearchView(ListView):
    model = Blog
    template_name = 'Blogs/search-view.html'
    # context_object_name = 'blogs'
    paginate_by = 2

    def get_context_data(self, **kwargs):

        context = super(BlogSearchView,self).get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query', "")
        query = self.request.GET.get('query')

        categories = Category.objects.all()
        category_id = self.request.GET.get('category_id')
        
        if query:
            if category_id:
                queryset = Blog.objects.filter(
                    Q(blog_title__icontains=query) |
                    Q(blog_text__icontains=query)
                ).distinct().order_by('-blog_date_time').filter(blog_category_id=category_id)
            else:
                queryset = Blog.objects.filter(
                    Q(blog_title__icontains=query) |
                    Q(blog_text__icontains=query)
                ).distinct().order_by('-blog_date_time')
            
            paginator = Paginator(queryset, self.paginate_by)
            page_number = self.request.GET.get("page")
            page_obj = paginator.get_page(page_number)

            try:
                blogs = paginator.page(page_number)
            except PageNotAnInteger:
                page_number = 1
                blogs = paginator.page(page_number)
            except EmptyPage:
                page_number = paginator.num_pages
                blogs = paginator.page(page_number)

            context['blogs'] = blogs
            context['page_obj'] = page_obj
            context['categories'] = categories
            return context

# api rest-view
class BlogAV(APIView):

    def get(self, request):

        blogs = Blog.objects.all().order_by('-blog_date_time')
        serializer = BlogSerializer(blogs, many=True)
        return Response(serializer.data)

    def post(self, request):

        serializer = BlogSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class BlogDetailAV(APIView):

    def get(self, request, pk):
        try:
            blog = Blog.objects.get(pk=pk)
        except Blog.DoesNotExist:
            return Response({'error':'Not found'}, status=status.HTTP_400_BAD_REQUEST)

        serializer = BlogSerializer(blog)
        return Response(serializer.data)

    def put(self, request, pk):
        blog = Blog.objects.get(pk=pk)
        serializer = Blog(blog, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        blog = Blog.objects.get(pk=pk)
        blog.delete()
        # return Response({'message':'this data is deleted'})
        return Response(status=status.HTTP_204_NO_CONTENT)


class WriterAV(APIView):

    def get(self, request):
        writer = Writer.objects.all()
        serializer = WriterSerializer(writer, many=True, context={'request': request})
        return Response(serializer.data)

    def post(self, request):
        serializer = WriterSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

Inkronix_Courses_Page_Updated/templates/Blogs/blog-form.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog writing page!</title>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
    rel="stylesheet" 
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" 
    crossorigin="anonymous">
</head>
<body>

    <!-- writer's blog post section -->
    <div class="container">

        <form method="POST" class="form-data" enctype="multipart/form-data">
            {% csrf_token %}
            <ul>{{ blog_form.as_p }}</ul>
            
            <button class="btn btn-primary my-4" type="submit">Submit</button>
        </form>
    </div>

    <script src="assets/js/main.js"></script>
</body>
</html>

Inkronix_Courses_Page_Updated/templates/Blogs/blog-view.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Page content-->
<div class="container">
    <div class="row">
        <!-- Blog entries-->
        <div class="col-lg-8">
            <!-- Featured blog posts-->
            <div class="card m-4 p-4" style="background-color:aliceblue">
                <img class="card-img-top" src="{{blog.blog_image.url}}"
                        style="width: 100%; height: 450px;" alt="..." />
                <div class="card-body">
                    <div class="large text-muted">{{blog.blog_date_time}}</div>
                    <div class="large text-muted">{{blog.writer_name.writer_name}} | {{blog.blog_category}}</div>
                    <h2 class="card-title">{{blog.blog_title}}</h2>
                    <p class="card-text">{{blog.blog_text}}</p>

                    <!--Comment Form-->
                    <div class="container">
                        <h2 class="my-4">Add your comment</h2>
                        <form method="post">
                            {% csrf_token %}
                            {{comment_form}}
                            <button class="btn btn-primary my-4" type="submit" name="blog_id" value="{{blog.id}}">Submit</button>
                        </form>

                        <!-- {% for c in blog.comment %}
                            <div class="container dark">{{c.your_comment}}</div>
                        {% empty %}
                            <p>No comments added.</p>
                        {% endfor %} -->

                        {% for c in comments %}
                            <div class="dropdown-divider"></div>
                            <div class="container darker">
                                <div>{{c.your_comment}}</div>
                                <div>{{c.name}}</div>
                                <span class="time-right">{{c.created_on}} | {{blog.blog_category}}</span>
                            </div>
                            <div class="dropdown-divider"></div>
                        {% empty %}
                            <p>No comments added.</p>
                        {% endfor %}

                    </div>
                    </div>
                </div>
            </div>


            <!-- Pagination-->
            <!-- <nav aria-label="Pagination">
                <hr class="my-0" />
                <ul class="pagination justify-content-center my-4"
                    style="background-color: rgb(218, 244, 246); border-radius: 1.0rem;">
                    <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true"
                            style="background-color:aliceblue;">Newer</a></li>
                    <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
                    <li class="page-item"><a class="page-link" href="#!" style="background-color:aliceblue;">2</a></li>
                    <li class="page-item"><a class="page-link" href="#!" style="background-color:aliceblue;">3</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#!"
                            style="background-color:aliceblue;">...</a></li>
                    <li class="page-item"><a class="page-link" href="#!" style="background-color:aliceblue;">15</a></li>
                    <li class="page-item"><a class="page-link" href="#!" style="background-color:aliceblue;">Older</a>
                    </li>
                </ul>
            </nav>
        </div> -->

        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Search widget -->
            <div class="card my-4" style="border-style: hidden;">
                <div class="card-header p-4 mb-4" style="background-color:aliceblue; border-radius: 0.8rem; color: rgb(10, 135, 177);">Search</div>
                <div class="card-body p-4" style="background-color: rgb(218, 244, 246); border-radius: 1.0rem;">
                    <div class="input-group">
                        <input class="form-control" type="text" style="background-color:aliceblue; border-style: hidden;" placeholder="Enter search term..."
                            aria-label="Enter search term..." aria-describedby="button-search" />
                        <button class="btn" id="button-search" type="button" style="font-size: small; background-color:rgb(148, 222, 227); border-radius: 1.0;">Search!</button>
                    </div>
                </div>
            </div>

            <!-- Categories widget-->
            <div class="card mb-4" style="border-style: hidden;">
                <div class="card-header p-4 mb-4" style="background-color:aliceblue; border-radius: 0.8rem; color: rgb(10, 135, 177);">Categories</div>
                <div class="card-body p-4" style="background-color: rgb(218, 244, 246); border-radius: 1.0rem;">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                {% for category in categories %}
                                {% if category.id < 5 %}
                                <li><a href="?category={{category.id}}">{{category.topic}}</a></li>
                                <!-- <li><a href="#!">HTML</a></li>
                                <li><a href="#!">Python</a></li> -->
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                {% for category in categories %}
                                {% if category.id >= 5 %}
                                <li><a href="?category={{category.id}}">{{category.topic}}</a></li>
                                {% endif %}
                                {% endfor %}
                                <!-- <li><a href="#!">CSS</a></li>
                                <li><a href="#!">Tutorials</a></li> -->
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Side widget-->
            <div class="card mb-4" style="border-style: hidden;">
                <div class="card-header p-4 mb-4" style="background-color:aliceblue; border-radius: 0.8rem; color: rgb(10, 135, 177);">Latest news</div>
                <div class="card-body p-4" style="background-color: rgb(218, 244, 246); border-radius: 1.0rem; color: black;">Course ads links or links of New updates about the platform</div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Inkronix_Courses_Page_Updated/templates/Blogs/blog.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Page header with logo and tagline-->
<header class="py-5 border-bottom mb-4" style="max-height: 420px; background-color:aliceblue; border-style: hidden;">
    <div class="container" style="max-height: 300px; background-color: rgb(218, 244, 246);">
        <img class="card-img-top" src="{% static 'assets\images\blog\home-background.jpg' %}" style="width: 100%; height:200px;" alt="..." />
        <div class="text-center my-4">
            <h1 class="fw-bolder">Welcome to our Blog!</h1>
            <p class="lead mb-1" style="color: rgb(10, 135, 177); font-size: large;">All blogs related to our courses, site updates and announcements</p>
        </div>
    </div>
</header>

<!-- Page content-->
<div class="container">
    <div class="row">
        <!-- Blog entries-->
        <div class="col-lg-8">
            <!-- Featured blog posts-->
            {% for blog in blogs %}
            <div class="card m-4 p-4" style="background-color:aliceblue; border-radius: 1.0rem;">
                <a href="/blog/{{blog.id}}"><img class="card-img-top" src="{{blog.blog_image.url}}"
                        style="width: 100%; height: 450px;" alt="..." /></a>
                <div class="card-body">
                    <div class="small text-muted">{{blog.blog_date_time}}</div>
                    <h2 class="small text-muted">{{blog.writer_name.writer_name}}</h2>
                    <h5 class="card-title">{{blog.blog_title}}</h5>
                    <p class="card-text">{{blog.blog_text|truncatewords:20}}</p>
                    <a class="btn" href="/blog/{{blog.id}}" style="background-color: rgb(148, 222, 227); font-size: small; border-radius: 0.8;">Read more →</a>
                </div>
            </div>
            {% empty %}
            <p>No blogs added.</p>
            {% endfor %}

            {% include "Blogs/blog_list.html" %}

        </div>
        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Search widget-->
            <div class="card my-4" style="border-style: hidden;">
                <div class="card-header p-4 mb-4" style="background-color:aliceblue; border-radius: 0.8rem; color: rgb(10, 135, 177);">Search</div>
                <div class="card-body p-4" style="background-color: rgb(218, 244, 246); border-radius: 1.0rem;">
                    <form action="search-view/" method="GET">
                        <div class="input-group">
                            <input class="form-cont rol" type="text" name="query" style="background-color:aliceblue; border-style: hidden;" placeholder="Enter search term..."
                                aria-label="Enter search term..." aria-describedby="button-search" />
                            <!-- adding submit type button to search other than using enter key -->
                        </div>
                        <button class="btn px-5" id="button-search" type="submit" style="font-size: small; background-color:rgb(148, 222, 227); border-radius: 1.0;">Search!</button>
                    </form>
                </div>
            </div>
            <!-- Categories widget-->
            <div class="card mb-4" style="border-style: hidden;">
                <div class="card-header p-4 mb-4" style="background-color:aliceblue; border-radius: 0.8rem; color: rgb(10, 135, 177);">Categories</div>
                <div class="card-body p-4" style="background-color: rgb(218, 244, 246); border-radius: 1.0rem;">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                {% for category in categories|slice:":4" %}
                                <li><a href="?category={{category.id}}">{{category.topic}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                {% for category in categories|slice:"4:" %}
                                <li><a href="?category={{category.id}}">{{category.topic}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Side widget-->
            <div class="card mb-4" style="border-style: hidden;">
                <div class="card-header p-4 mb-4" style="background-color:aliceblue; border-radius: 0.8rem; color: rgb(10, 135, 177);">Latest news</div>
                <div class="card-body p-4" style="background-color: rgb(218, 244, 246); border-radius: 1.0rem; color: black;">Course ads links or links of New updates about the platform</div>
            </div>
            {% if request.user.is_authenticated and request.user.is_staff %}
            <div class="card mb-4" style="border-style: hidden;">
                <div class="card-header p-4 mb-4" style="background-color:aliceblue; border-radius: 0.8rem; color: rgb(10, 135, 177);">
                    <p>Welcome writer {{request.user}}!</p>
                    <form action="blog-form" method="GET">
                        <button class="btn" type="submit" style="font-size: small; background-color:rgb(148, 222, 227); border-style: hidden;">Add new blogs</button>
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

Inkronix_Courses_Page_Updated/templates/Blogs/blog_list.html
<!-- When you name your Django template blog_list.html, both your PaginatedListView class or your function based view can find the template.  -->
    <!-- {% for page_number in page_obj.paginator.page_range %}
    <h1>{{page_obj.paginator.page_range}}</h1>
        <a
            href="paginated-blogs/?page="
            class="{% if page_number == page_obj.number %}current{% endif %}"
        >
            {{page_number}}
        </a>
    {% endfor %} -->

    <!-- Pagination-->
    <nav aria-label="Pagination" style="padding-right: 20px;">
        <hr class="my-0" />
        <ul class="pagination justify-content-center my-4" style="background-color: rgb(218, 244, 246); border-radius: 1.0rem;">

            {% if page_obj.has_previous %}
            <li class="page-item active">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="false"
                style="background-color:aliceblue; color: rgb(10, 135, 177);">&laquo; Newer</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true"
                style="background-color:aliceblue; color: rgb(10, 135, 177);">&laquo; Newer</a>
            </li>
            {% endif %}

            {% for page_number in page_obj.paginator.page_range %}
            {% if page_number == page_obj.number and page_obj.has_next in page_obj.paginator.page_range %}
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}" style="background-color:aliceblue; color: rgb(10, 135, 177);">{{page_obj.previous_page_number}}</a></li>
            {% endif %}
            <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}</a></li>
            <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}" style="background-color:aliceblue; color: rgb(10, 135, 177);">{{page_obj.next_page_number}}</a></li>
            {% endif %}
            {% endfor %}

            <li class="page-item disabled"><a class="page-link" href="#!" style="background-color:aliceblue;">...</a></li>

            {% if page_obj.has_next in page_obj.paginator.page_range %}
            <li class="page-item"><a class="page-link" href="?page={{page_obj.paginator.num_pages}}" style="background-color:aliceblue; color: rgb(10, 135, 177);">{{page_obj.paginator.num_pages}}</a></li>
            <!-- <li class="page-item"><a class="page-link" href="?page={{blogs|length}}" style="background-color:aliceblue; color: rgb(10, 135, 177);">{{blogs|length}}</a></li> -->
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" tabindex="+1" aria-disabled="false" style="background-color:aliceblue; color: rgb(10, 135, 177);">Older  &raquo;</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="?page={{ page_obj.current }}" tabindex="+1" aria-disabled="true" style="background-color:aliceblue; color: rgb(10, 135, 177);">Older  &raquo;</a></li>
            {% endif %}

        </ul>
    </nav>